---
version: '3.8'
services:
  mongodb:
    image: mongo
    hostname: mongodb
    container_name: mongodb    
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      # MONGO_INITDB_DATABASE: staging
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - data-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root123
      ME_CONFIG_MONGODB_URL: mongodb://root:root123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - data-network

volumes:
  mongodb:
  mongoconfig:

networks:
  data-network:
    external: true